import { DRAWING_GRADES, suggestedDrawingGrade } from '../../src/drawingGrades';

type Submission = { id:string; displayName:string; submittedAt:string; moderationStatus:string; score:number|null; grade:string|null; comment:string|null; judgedAt:string|null; challenge:{id:string;title:string;imageUrl:string}; imageUrl:string; resultUrl:string };
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const loginCard=$('#login-card'),loginForm=$('#login-form') as HTMLFormElement,loginStatus=$('#login-status'),desk=$('#desk'),deskStatus=$('#desk-status'),entries=$('#entries');
let adminKey=localStorage.getItem('drawing-hand-admin-key')??'';
function setStatus(t:HTMLElement,m:string,e=false){t.textContent=m;t.dataset.error=e?'true':'false'}
function escapeHtml(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
function gradeOptions(selected:string|null){return DRAWING_GRADES.map(({label,min,max})=>`<option value="${escapeHtml(label)}" ${selected===label?'selected':''}>${escapeHtml(label)} (${min}–${max})</option>`).join('')}
function duplicateGroups(submissions:Submission[]){const groups=new Map<string,Submission[]>();for(const s of submissions){const key=`${s.challenge.id}\0${s.displayName.trim().toLocaleLowerCase()}`;groups.set(key,[...(groups.get(key)??[]),s])}return groups}
function render(submissions:Submission[]){
 if(!submissions.length){entries.innerHTML='<div class="card empty"><h2>No drawings yet.</h2><p>When somebody submits an entry, it will appear here.</p></div>';return}
 const groups=duplicateGroups(submissions);
 entries.innerHTML=submissions.map((submission,index)=>{const judged=Boolean(submission.judgedAt),score=submission.score??'',selectedGrade=submission.grade??'',suggested=typeof submission.score==='number'?suggestedDrawingGrade(submission.score):null;const group=groups.get(`${submission.challenge.id}\0${submission.displayName.trim().toLocaleLowerCase()}`)??[];const keepCandidates=group.filter(item=>item.id!==submission.id);const duplicateControl=keepCandidates.length?`<div class="duplicate-control"><p class="note"><strong>Possible duplicate:</strong> ${group.length} entries use this name for this challenge.</p><label>Keep this copy instead<select class="duplicate-keep">${keepCandidates.map(item=>`<option value="${escapeHtml(item.id)}">${item.judgedAt?'Judged':'Waiting'} · ${new Date(item.submittedAt).toLocaleString()}</option>`).join('')}</select></label><button type="button" class="remove-duplicate">Remove this duplicate</button><p class="status duplicate-status" aria-live="polite"></p></div>`:'';
 return `<article class="card ${judged?'judged':''}" data-entry="${escapeHtml(submission.id)}"><div class="meta"><span class="pill">${judged?'Judged':`Waiting #${index+1}`}</span><strong>${escapeHtml(submission.displayName)}</strong><span class="note">${new Date(submission.submittedAt).toLocaleString()}</span></div><h2>${escapeHtml(submission.challenge.title)}</h2><div class="entry-grid"><figure class="image-box"><figcaption>Elijah's challenge</figcaption><img src="${escapeHtml(submission.challenge.imageUrl)}" alt="Elijah's challenge drawing"></figure><figure class="image-box"><figcaption>${escapeHtml(submission.displayName)}'s drawing</figcaption><img src="${escapeHtml(submission.imageUrl)}" alt="Submitted drawing by ${escapeHtml(submission.displayName)}"></figure></div><form class="judge-form"><div class="fields"><label>Score out of 10<input name="score" type="number" min="0" max="10" step="0.001" inputmode="decimal" value="${score}" required></label><p class="note suggestion">${suggested?`Suggested grade: ${escapeHtml(suggested)}`:(submission.score===null?'Enter a score to see the suggested grade.':'No automatic grade for this score — Elijah chooses.')}</p><label>Final grade<select name="grade" required><option value="" ${selectedGrade?'':'selected'} disabled>Choose grade</option>${gradeOptions(selectedGrade)}</select></label><label>Elijah's comment (optional)<textarea name="comment" maxlength="280" placeholder="What did you like?">${escapeHtml(submission.comment??'')}</textarea></label><label class="check"><input name="showInGallery" type="checkbox" ${submission.moderationStatus==='approved'?'checked':''}> <span>Allow this drawing to appear in a future public gallery</span></label></div><button type="submit">${judged?'Update result':'Save result'}</button><a class="result-link" href="${escapeHtml(submission.resultUrl)}" target="_blank" rel="noreferrer">Open private result ↗</a><p class="status form-status" aria-live="polite"></p></form>${duplicateControl}</article>`}).join('');
 for(const article of entries.querySelectorAll<HTMLElement>('[data-entry]')){const form=article.querySelector<HTMLFormElement>('.judge-form')!,scoreInput=form.elements.namedItem('score') as HTMLInputElement,gradeSelect=form.elements.namedItem('grade') as HTMLSelectElement,suggestion=article.querySelector<HTMLElement>('.suggestion')!,status=article.querySelector<HTMLElement>('.form-status')!,pill=article.querySelector<HTMLElement>('.pill')!,submitButton=form.querySelector<HTMLButtonElement>('button[type="submit"]')!;
 scoreInput.addEventListener('input',()=>{if(!scoreInput.value.trim()){suggestion.textContent='Enter a score to see the suggested grade.';return}const g=suggestedDrawingGrade(Number(scoreInput.value));if(g){suggestion.textContent=`Suggested grade: ${g}`;gradeSelect.value=g}else suggestion.textContent='No automatic grade for this score — Elijah chooses.'});
 form.addEventListener('submit',async event=>{event.preventDefault();const wasWaiting=!article.classList.contains('judged'),data=new FormData(form),payload={submissionId:article.dataset.entry,score:Number(data.get('score')),grade:String(data.get('grade')||''),comment:String(data.get('comment')||''),showInGallery:data.get('showInGallery')==='on'};setStatus(status,'Saving Elijah’s result…');try{const response=await fetch('/api/drawing-judging',{method:'POST',headers:{'content-type':'application/json','x-drawing-hand-key':adminKey},body:JSON.stringify(payload)}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Could not save the result.');setStatus(status,'Saved. The private result link now shows Elijah’s judgement.');article.classList.add('judged');pill.textContent='Judged';submitButton.textContent='Update result';if(wasWaiting){const waiting=entries.querySelectorAll<HTMLElement>('[data-entry]:not(.judged)').length;setStatus(deskStatus,`${waiting} drawing${waiting===1?'':'s'} waiting for Elijah.`)}}catch(error){setStatus(status,error instanceof Error?error.message:'Could not save the result.',true)}});
 const removeButton=article.querySelector<HTMLButtonElement>('.remove-duplicate'),keepSelect=article.querySelector<HTMLSelectElement>('.duplicate-keep'),duplicateStatus=article.querySelector<HTMLElement>('.duplicate-status');if(removeButton&&keepSelect&&duplicateStatus)removeButton.addEventListener('click',async()=>{const keep=keepSelect.value;if(!keep)return;const current=submissions.find(item=>item.id===article.dataset.entry),survivor=submissions.find(item=>item.id===keep);if(!current||!survivor)return;const ok=confirm(`Remove this ${current.judgedAt?'judged':'waiting'} copy for ${current.displayName}? The ${survivor.judgedAt?'judged':'waiting'} copy from ${new Date(survivor.submittedAt).toLocaleString()} will be kept. This cannot be undone.`);if(!ok)return;setStatus(duplicateStatus,'Removing duplicate…');removeButton.disabled=true;try{const response=await fetch('/api/drawing-judging',{method:'DELETE',headers:{'content-type':'application/json','x-drawing-hand-key':adminKey},body:JSON.stringify({submissionId:current.id,duplicateOfId:survivor.id})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Could not remove the duplicate.');await loadDesk()}catch(error){removeButton.disabled=false;setStatus(duplicateStatus,error instanceof Error?error.message:'Could not remove the duplicate.',true)}})
 }
}
async function loadDesk(){if(!adminKey)return;setStatus(loginStatus,'Opening desk…');const response=await fetch('/api/drawing-judging',{headers:{accept:'application/json','x-drawing-hand-key':adminKey}}),payload=await response.json() as {error?:string;submissions?:Submission[]};if(!response.ok||!payload.submissions)throw new Error(payload.error||'Could not open the Judging Desk.');localStorage.setItem('drawing-hand-admin-key',adminKey);loginCard.hidden=true;desk.hidden=false;const waiting=payload.submissions.filter(item=>!item.judgedAt).length;setStatus(deskStatus,`${waiting} drawing${waiting===1?'':'s'} waiting for Elijah.`);render(payload.submissions)}
loginForm.addEventListener('submit',async event=>{event.preventDefault();adminKey=String(new FormData(loginForm).get('adminKey')||'').trim();if(!adminKey)return;try{await loadDesk()}catch(error){setStatus(loginStatus,error instanceof Error?error.message:'Could not open the Judging Desk.',true)}});
if(adminKey){(loginForm.elements.namedItem('adminKey') as HTMLInputElement).value=adminKey;loadDesk().catch(error=>setStatus(loginStatus,error instanceof Error?error.message:'Could not open the Judging Desk.',true))}
