import { preparePhotoForMicroblog } from '../packages/publishing-core/image-optimization';
import { DRAWING_GRADES, suggestedDrawingGrade } from '../src/drawingGrades';

type Challenge = { id:string; title:string; difficulty:string|null; imageUrl:string; elijahScore:number|null; elijahGrade:string|null };
type PreparedPreview = { file: File; url: string };
type SavedEntry = { token:string; resultUrl:string; displayName:string; challengeTitle:string; submittedAt:string };
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const challengeList=$('#challenge-list'),challengesSection=$('#challenges-section'),noChallenge=$('#no-challenge'),submissionCard=$('#submission-card'),selectedChallenge=$('#selected-challenge'),submissionStatus=$('#submission-status'),adminPanel=$('#admin-panel'),adminStatus=$('#admin-status'),myEntries=$('#my-entries'),myEntriesList=$('#my-entries-list'),findGradeStatus=$('#find-grade-status'),findGradeChallenge=$('#find-grade-challenge') as HTMLSelectElement;
const submissionForm=$('#submission-form') as HTMLFormElement,submissionPreview=$('#submission-preview') as HTMLImageElement,adminForm=$('#admin-form') as HTMLFormElement,adminPreview=$('#admin-preview') as HTMLImageElement,findGradeForm=$('#find-grade-form') as HTMLFormElement;
let challenges:Challenge[]=[],activeChallenge:Challenge|null=null,submissionPrepared:PreparedPreview|null=null,adminPrepared:PreparedPreview|null=null,submissionSelectionVersion=0,adminSelectionVersion=0;
const entriesKey='drawing-hand-entries';
function setStatus(t:HTMLElement,m:string,e=false){t.textContent=m;t.dataset.error=e?'true':'false'}
function clearPreparedPreview(p:HTMLImageElement,x:PreparedPreview|null){if(x)URL.revokeObjectURL(x.url);p.hidden=true;p.removeAttribute('src')}
async function preparedImage(f:File){return (await preparePhotoForMicroblog(f,f.type)).file}
async function preparePreview(f:File):Promise<PreparedPreview>{const file=await preparedImage(f);return{file,url:URL.createObjectURL(file)}}
function savedEntries():SavedEntry[]{try{return JSON.parse(localStorage.getItem(entriesKey)||'[]') as SavedEntry[]}catch{return[]}}
function rememberEntry(entry:SavedEntry){try{const entries=savedEntries();localStorage.setItem(entriesKey,JSON.stringify([entry,...entries.filter(item=>item.token!==entry.token)].slice(0,20)))}catch{}}
function renderMyEntries(){const entries=savedEntries();myEntries.hidden=!entries.length;if(!entries.length)return;myEntriesList.replaceChildren();for(const entry of entries){const link=document.createElement('a');link.className='saved-entry';link.href=entry.resultUrl;const title=document.createElement('strong');title.textContent=entry.challengeTitle;const name=document.createElement('span');name.textContent=`${entry.displayName} — open private result`;link.append(title,name);myEntriesList.append(link)}}
function selfGradeText(challenge:Challenge){const hasSelf=challenge.elijahScore!==null||!!challenge.elijahGrade;if(!hasSelf)return'';return`Elijah gave his own drawing: ${challenge.elijahScore!==null?`${challenge.elijahScore}/10`:''}${challenge.elijahScore!==null&&challenge.elijahGrade?' — ':''}${challenge.elijahGrade??''}`}
function chooseChallenge(challenge:Challenge){activeChallenge=challenge;selectedChallenge.textContent=`You chose: ${challenge.title}`;submissionCard.hidden=false;setStatus(submissionStatus,'');document.querySelectorAll<HTMLButtonElement>('[data-choose-challenge]').forEach(button=>{const selected=button.dataset.chooseChallenge===challenge.id;button.textContent=selected?'Selected':'Draw this one';button.classList.toggle('secondary',!selected)});submissionCard.scrollIntoView({behavior:'smooth',block:'start'})}
function renderChallenges(){challengeList.replaceChildren();for(const challenge of challenges){const card=document.createElement('article');card.className='card challenge-card';const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.style.marginTop='0';eyebrow.textContent=challenge===challenges[0]?'Newest challenge':'Challenge';const title=document.createElement('h3');title.textContent=challenge.title;card.append(eyebrow,title);if(challenge.difficulty){const difficulty=document.createElement('p');difficulty.className='note';difficulty.textContent=`Difficulty: ${challenge.difficulty}`;card.append(difficulty)}const image=document.createElement('img');image.className='challenge-image';image.src=challenge.imageUrl;image.alt=`Elijah's challenge drawing: ${challenge.title}`;card.append(image);const self=selfGradeText(challenge);if(self){const grade=document.createElement('p');grade.className='self-grade';grade.textContent=self;card.append(grade)}const button=document.createElement('button');button.type='button';button.dataset.chooseChallenge=challenge.id;button.textContent=activeChallenge?.id===challenge.id?'Selected':'Draw this one';if(activeChallenge?.id!==challenge.id)button.classList.add('secondary');button.addEventListener('click',()=>chooseChallenge(challenge));card.append(button);challengeList.append(card)}}
function renderFindGradeChallenges(){const selected=findGradeChallenge.value;findGradeChallenge.replaceChildren(new Option('Choose a challenge…',''));for(const challenge of challenges)findGradeChallenge.append(new Option(challenge.title,challenge.id));if(challenges.some(challenge=>challenge.id===selected))findGradeChallenge.value=selected}
async function loadChallenges(){const r=await fetch('/api/drawing-challenges',{headers:{accept:'application/json'}});if(!r.ok)throw new Error('Could not load the challenges.');const p=await r.json() as {challenges?:Challenge[];challenge?:Challenge|null};challenges=p.challenges??(p.challenge?[p.challenge]:[]);renderFindGradeChallenges();if(!challenges.length){activeChallenge=null;challengesSection.hidden=true;submissionCard.hidden=true;noChallenge.hidden=false;return}noChallenge.hidden=true;challengesSection.hidden=false;const previous=activeChallenge?.id;activeChallenge=challenges.find(challenge=>challenge.id===previous)??challenges[0];renderChallenges();selectedChallenge.textContent=`You chose: ${activeChallenge.title}`;submissionCard.hidden=false}
findGradeForm.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(findGradeForm),displayName=String(d.get('displayName')||'').trim(),challengeId=String(d.get('challengeId')||'').trim();if(!displayName||!challengeId){setStatus(findGradeStatus,'Enter the name you used and choose the challenge.',true);return}const challenge=challenges.find(item=>item.id===challengeId);try{setStatus(findGradeStatus,'Looking for your drawing…');const r=await fetch('/api/drawing-find-grade',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({displayName,challengeId})}),p=await r.json() as {error?:string;found?:boolean;message?:string;resultToken?:string;resultUrl?:string};if(!r.ok)throw new Error(p.error||'Could not look for your grade.');if(!p.found||!p.resultToken||!p.resultUrl){setStatus(findGradeStatus,p.message||'We could not find one matching drawing.',true);return}rememberEntry({token:p.resultToken,resultUrl:p.resultUrl,displayName,challengeTitle:challenge?.title||'Recovered drawing',submittedAt:new Date().toISOString()});renderMyEntries();setStatus(findGradeStatus,'Found it! Opening your private result…');location.assign(p.resultUrl)}catch(e){setStatus(findGradeStatus,e instanceof Error?e.message:'Could not look for your grade.',true)}});
const submissionImageInput=submissionForm.elements.namedItem('image') as HTMLInputElement;submissionImageInput.addEventListener('change',async()=>{const v=++submissionSelectionVersion;clearPreparedPreview(submissionPreview,submissionPrepared);submissionPrepared=null;const f=submissionImageInput.files?.[0];if(!f)return;setStatus(submissionStatus,'Preparing preview…');try{const p=await preparePreview(f);if(v!==submissionSelectionVersion){URL.revokeObjectURL(p.url);return}submissionPrepared=p;submissionPreview.src=p.url;submissionPreview.hidden=false;setStatus(submissionStatus,'')}catch(e){if(v===submissionSelectionVersion)setStatus(submissionStatus,e instanceof Error?e.message:'Could not preview that drawing.',true)}});
submissionForm.addEventListener('submit',async e=>{e.preventDefault();if(!activeChallenge)return;const d=new FormData(submissionForm),picked=d.get('image');if(!(picked instanceof File)||!picked.size){setStatus(submissionStatus,'Choose a photo of your drawing first.',true);return}try{const image=submissionPrepared?.file??await preparedImage(picked);d.set('image',image,image.name);d.set('challengeId',activeChallenge.id);setStatus(submissionStatus,'Sending your drawing to Elijah…');const r=await fetch('/api/drawing-submissions',{method:'POST',body:d}),p=await r.json() as {error?:string;submission?:{resultToken:string;resultUrl:string;displayName?:string}};if(!r.ok||!p.submission)throw new Error(p.error||'Your drawing could not be submitted.');const displayName=String(d.get('displayName')||'Your entry');rememberEntry({token:p.submission.resultToken,resultUrl:p.submission.resultUrl,displayName,challengeTitle:activeChallenge.title,submittedAt:new Date().toISOString()});location.assign(p.submission.resultUrl)}catch(e){setStatus(submissionStatus,e instanceof Error?e.message:'Your drawing could not be submitted.',true)}});
if(new URL(location.href).searchParams.get('admin')==='1'){adminPanel.hidden=false;const k=localStorage.getItem('drawing-hand-admin-key');if(k)(adminForm.elements.namedItem('adminKey') as HTMLInputElement).value=k}
const gradeSelect=adminForm.elements.namedItem('elijahGrade') as HTMLSelectElement;for(const {label} of DRAWING_GRADES){const o=document.createElement('option');o.value=label;o.textContent=label;gradeSelect.append(o)}
const scoreInput=adminForm.elements.namedItem('elijahScore') as HTMLInputElement;scoreInput.addEventListener('input',()=>{const n=Number(scoreInput.value);const g=scoreInput.value===''?null:suggestedDrawingGrade(n);gradeSelect.options[0].textContent=g?`Use suggested grade (${g})`:'Use suggested grade'});
const adminImageInput=adminForm.elements.namedItem('image') as HTMLInputElement;adminImageInput.addEventListener('change',async()=>{const v=++adminSelectionVersion;clearPreparedPreview(adminPreview,adminPrepared);adminPrepared=null;const f=adminImageInput.files?.[0];if(!f)return;setStatus(adminStatus,"Preparing Elijah's preview…");try{const p=await preparePreview(f);if(v!==adminSelectionVersion){URL.revokeObjectURL(p.url);return}adminPrepared=p;adminPreview.src=p.url;adminPreview.hidden=false;setStatus(adminStatus,'')}catch(e){if(v===adminSelectionVersion)setStatus(adminStatus,e instanceof Error?e.message:"Could not preview Elijah's picture.",true)}});
adminForm.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(adminForm),key=String(d.get('adminKey')||'').trim(),picked=d.get('image');if(!key){setStatus(adminStatus,'Enter the Drawing Hand admin key.',true);return}if(!(picked instanceof File)||!picked.size){setStatus(adminStatus,"Choose Elijah's challenge picture.",true);return}try{const image=adminPrepared?.file??await preparedImage(picked);d.set('image',image,image.name);d.delete('adminKey');setStatus(adminStatus,'Publishing challenge…');const r=await fetch('/api/drawing-challenges',{method:'POST',headers:{'x-drawing-hand-key':key},body:d}),p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error||'The challenge could not be published.');localStorage.setItem('drawing-hand-admin-key',key);adminForm.reset();(adminForm.elements.namedItem('adminKey') as HTMLInputElement).value=key;gradeSelect.options[0].textContent='Use suggested grade';adminSelectionVersion++;clearPreparedPreview(adminPreview,adminPrepared);adminPrepared=null;setStatus(adminStatus,'Challenge published. The five newest challenges can stay open together.');await loadChallenges()}catch(e){setStatus(adminStatus,e instanceof Error?e.message:'The challenge could not be published.',true)}});
renderMyEntries();
loadChallenges().catch(e=>{challengesSection.hidden=true;submissionCard.hidden=true;noChallenge.hidden=false;noChallenge.textContent=e instanceof Error?e.message:'Could not load the challenges.'});
