import { preparePhotoForMicroblog } from '../packages/publishing-core/image-optimization';
import { DRAWING_GRADES, suggestedDrawingGrade } from '../src/drawingGrades';

type Challenge = { id:string; title:string; difficulty:string|null; imageUrl:string; elijahScore:number|null; elijahGrade:string|null };
type PreparedPreview = { file: File; url: string };
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const challengeCard=$('#challenge-card'),challengeTitle=$('#challenge-title'),challengeDifficulty=$('#challenge-difficulty'),challengeSelfGrade=$('#challenge-self-grade'),noChallenge=$('#no-challenge'),submissionStatus=$('#submission-status'),adminPanel=$('#admin-panel'),adminStatus=$('#admin-status');
const challengeImage=$('#challenge-image') as HTMLImageElement,submissionForm=$('#submission-form') as HTMLFormElement,submissionPreview=$('#submission-preview') as HTMLImageElement,adminForm=$('#admin-form') as HTMLFormElement,adminPreview=$('#admin-preview') as HTMLImageElement;
let activeChallenge:Challenge|null=null,submissionPrepared:PreparedPreview|null=null,adminPrepared:PreparedPreview|null=null,submissionSelectionVersion=0,adminSelectionVersion=0;
function setStatus(t:HTMLElement,m:string,e=false){t.textContent=m;t.dataset.error=e?'true':'false'}
function clearPreparedPreview(p:HTMLImageElement,x:PreparedPreview|null){if(x)URL.revokeObjectURL(x.url);p.hidden=true;p.removeAttribute('src')}
async function preparedImage(f:File){return (await preparePhotoForMicroblog(f,f.type)).file}
async function preparePreview(f:File):Promise<PreparedPreview>{const file=await preparedImage(f);return{file,url:URL.createObjectURL(file)}}
async function loadChallenge(){const r=await fetch('/api/drawing-challenges',{headers:{accept:'application/json'}});if(!r.ok)throw new Error('Could not load the current challenge.');const p=await r.json() as {challenge:Challenge|null};activeChallenge=p.challenge;if(!activeChallenge){challengeCard.hidden=true;noChallenge.hidden=false;return}noChallenge.hidden=true;challengeCard.hidden=false;challengeTitle.textContent=activeChallenge.title;challengeDifficulty.textContent=activeChallenge.difficulty?`Difficulty: ${activeChallenge.difficulty}`:'';challengeDifficulty.hidden=!activeChallenge.difficulty;challengeImage.src=activeChallenge.imageUrl;challengeImage.alt=`Elijah's challenge drawing: ${activeChallenge.title}`;const hasSelf=activeChallenge.elijahScore!==null||!!activeChallenge.elijahGrade;challengeSelfGrade.textContent=hasSelf?`Elijah gave his own drawing: ${activeChallenge.elijahScore!==null?`${activeChallenge.elijahScore}/10`:''}${activeChallenge.elijahScore!==null&&activeChallenge.elijahGrade?' — ':''}${activeChallenge.elijahGrade??''}`:'';challengeSelfGrade.hidden=!hasSelf}
const submissionImageInput=submissionForm.elements.namedItem('image') as HTMLInputElement;submissionImageInput.addEventListener('change',async()=>{const v=++submissionSelectionVersion;clearPreparedPreview(submissionPreview,submissionPrepared);submissionPrepared=null;const f=submissionImageInput.files?.[0];if(!f)return;setStatus(submissionStatus,'Preparing preview…');try{const p=await preparePreview(f);if(v!==submissionSelectionVersion){URL.revokeObjectURL(p.url);return}submissionPrepared=p;submissionPreview.src=p.url;submissionPreview.hidden=false;setStatus(submissionStatus,'')}catch(e){if(v===submissionSelectionVersion)setStatus(submissionStatus,e instanceof Error?e.message:'Could not preview that drawing.',true)}});
submissionForm.addEventListener('submit',async e=>{e.preventDefault();if(!activeChallenge)return;const d=new FormData(submissionForm),picked=d.get('image');if(!(picked instanceof File)||!picked.size){setStatus(submissionStatus,'Choose a photo of your drawing first.',true);return}try{const image=submissionPrepared?.file??await preparedImage(picked);d.set('image',image,image.name);d.set('challengeId',activeChallenge.id);setStatus(submissionStatus,'Sending your drawing to Elijah…');const r=await fetch('/api/drawing-submissions',{method:'POST',body:d}),p=await r.json() as {error?:string;submission?:{resultUrl:string}};if(!r.ok||!p.submission)throw new Error(p.error||'Your drawing could not be submitted.');submissionForm.reset();submissionSelectionVersion++;clearPreparedPreview(submissionPreview,submissionPrepared);submissionPrepared=null;submissionStatus.innerHTML=`Sent! Elijah can now judge your drawing. <a href="${p.submission.resultUrl}">Keep this private result link</a>.`}catch(e){setStatus(submissionStatus,e instanceof Error?e.message:'Your drawing could not be submitted.',true)}});
if(new URL(location.href).searchParams.get('admin')==='1'){adminPanel.hidden=false;const k=localStorage.getItem('drawing-hand-admin-key');if(k)(adminForm.elements.namedItem('adminKey') as HTMLInputElement).value=k}
const gradeSelect=adminForm.elements.namedItem('elijahGrade') as HTMLSelectElement;for(const {label} of DRAWING_GRADES){const o=document.createElement('option');o.value=label;o.textContent=label;gradeSelect.append(o)}
const scoreInput=adminForm.elements.namedItem('elijahScore') as HTMLInputElement;scoreInput.addEventListener('input',()=>{const n=Number(scoreInput.value);const g=scoreInput.value===''?null:suggestedDrawingGrade(n);gradeSelect.options[0].textContent=g?`Use suggested grade (${g})`:'Use suggested grade'});
const adminImageInput=adminForm.elements.namedItem('image') as HTMLInputElement;adminImageInput.addEventListener('change',async()=>{const v=++adminSelectionVersion;clearPreparedPreview(adminPreview,adminPrepared);adminPrepared=null;const f=adminImageInput.files?.[0];if(!f)return;setStatus(adminStatus,"Preparing Elijah's preview…");try{const p=await preparePreview(f);if(v!==adminSelectionVersion){URL.revokeObjectURL(p.url);return}adminPrepared=p;adminPreview.src=p.url;adminPreview.hidden=false;setStatus(adminStatus,'')}catch(e){if(v===adminSelectionVersion)setStatus(adminStatus,e instanceof Error?e.message:"Could not preview Elijah's picture.",true)}});
adminForm.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(adminForm),key=String(d.get('adminKey')||'').trim(),picked=d.get('image');if(!key){setStatus(adminStatus,'Enter the Drawing Hand admin key.',true);return}if(!(picked instanceof File)||!picked.size){setStatus(adminStatus,"Choose Elijah's challenge picture.",true);return}try{const image=adminPrepared?.file??await preparedImage(picked);d.set('image',image,image.name);d.delete('adminKey');setStatus(adminStatus,'Publishing challenge…');const r=await fetch('/api/drawing-challenges',{method:'POST',headers:{'x-drawing-hand-key':key},body:d}),p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error||'The challenge could not be published.');localStorage.setItem('drawing-hand-admin-key',key);adminForm.reset();(adminForm.elements.namedItem('adminKey') as HTMLInputElement).value=key;gradeSelect.options[0].textContent='Use suggested grade';adminSelectionVersion++;clearPreparedPreview(adminPreview,adminPrepared);adminPrepared=null;setStatus(adminStatus,'Challenge published. It is now open for drawings.');await loadChallenge()}catch(e){setStatus(adminStatus,e instanceof Error?e.message:'The challenge could not be published.',true)}});
loadChallenge().catch(e=>{challengeCard.hidden=true;noChallenge.hidden=false;noChallenge.textContent=e instanceof Error?e.message:'Could not load the current challenge.'});
